<a href="https://colab.research.google.com/github/VitaliPopov/PYTHON_HW/blob/main/python_sem9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
datafr = pd.read_csv('sample_data/california_housing_test.csv', sep = ",", encoding = "utf-8")
datafr.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [5]:
datafr.shape

(3000, 9)

In [8]:
datafr.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [9]:
datafr.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [11]:
# Задача №59. Решение в группах
# 1. Проверить есть ли в файле пустые значения
# 2. Показать median_house_value где median_income < 2
# 3. Показать данные в первых 2 столбцах
# 4. Выбрать данные где housing_median_age < 20 и
# median_house_value > 70000
datafr.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [16]:
datafr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [18]:
datafr[datafr['median_income']<2]['median_house_value']

5        67000.0
6        67000.0
16      181300.0
28      350000.0
43       79300.0
          ...
2943     57200.0
2964     91300.0
2985    109400.0
2986     85400.0
2995    225000.0
Name: median_house_value, Length: 360, dtype: float64

In [22]:
for item in datafr.columns[:2]:
  print(datafr[item])

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64
0       37.37
1       34.26
2       33.78
3       33.82
4       36.33
        ...
2995    34.42
2996    34.06
2997    36.30
2998    34.10
2999    34.42
Name: latitude, Length: 3000, dtype: float64

In [25]:
datafr[(datafr['housing_median_age']<20)&(datafr['median_house_value']<70000)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
244,-114.98,33.07,18.0,1183.0,363.0,374.0,127.0,3.1607,57500.0
269,-121.30,37.95,9.0,674.0,242.0,575.0,193.0,2.2024,45000.0
333,-122.70,38.35,14.0,1555.0,369.0,493.0,335.0,1.6033,67500.0
358,-121.59,39.15,5.0,1922.0,489.0,938.0,439.0,2.0474,61300.0
483,-115.90,32.69,18.0,414.0,86.0,98.0,54.0,1.5417,57500.0
495,-122.29,37.82,2.0,158.0,43.0,94.0,57.0,2.5625,60000.0
546,-119.57,36.09,6.0,2015.0,413.0,992.0,319.0,2.3889,53200.0
572,-122.20,39.75,18.0,2603.0,576.0,1616.0,588.0,2.0192,63700.0
585,-116.89,33.79,12.0,701.0,130.0,434.0,110.0,2.0577,56700.0
769,-119.27,35.87,12.0,972.0,269.0,1134.0,286.0,1.6300,49500.0
804,-122.23,40.15,14.0,2297.0,573.0,1637.0,551.0,1.7870,51600.0
892,-121.10,38.95,17.0,1475.0,403.0,943.0,363.0,2.1287,55300.0
903,-123.41,40.61,17.0,769.0,205.0,301.0,126.0,1.7875,55000.0
1031,-123.08,40.40,10.0,365.0,102.0,140.0,49.0,1.7969,37500.0
1073,-119.35,36.19,6.0,958.0,226.0,734.0,230.0,1.0349,67800.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
1145,-114.61,33.62,16.0,1187.0,261.0,1115.0,242.0,2.1759,61500.0
1463,-119.71,36.81,19.0,2282.0,550.0,1034.0,500.0,1.6618,69700.0
1539,-120.79,37.08,9.0,97.0,20.0,91.0,22.0,2.9063,55000.0
1595,-114.55,32.80,19.0,2570.0,820.0,1431.0,608.0,1.2750,56100.0
1636,-119.29,35.76,15.0,3938.0,789.0,3500.0,768.0,2.1295,59800.0
1736,-119.23,35.74,16.0,2275.0,659.0,1914.0,614.0,2.0330,68400.0
1784,-119.29,36.54,18.0,2581.0,628.0,2732.0,592.0,1.8429,58300.0
1841,-122.25,40.15,15.0,1677.0,346.0,858.0,327.0,2.4375,59200.0
1903,-116.28,32.84,18.0,382.0,128.0,194.0,69.0,2.5179,58800.0
2072,-116.29,34.18,15.0,4203.0,966.0,1756.0,695.0,2.1820,60800.0
2093,-117.77,33.69,16.0,1666.0,341.0,479.0,336.0,2.1406,55000.0
2157,-122.20,39.93,9.0,1296.0,287.0,768.0,260.0,1.9191,54400.0
2587,-119.72,36.82,15.0,946.0,239.0,550.0,246.0,2.2639,52500.0
2592,-122.45,40.61,17.0,785.0,155.0,417.0,136.0,2.3289,58200.0
2627,-121.57,39.48,15.0,202.0,54.0,145.0,40.0,0.8252,42500.0
2670,-119.32,36.19,11.0,3136.0,620.0,2013.0,583.0,3.3350,69700.0
2688,-122.53,39.09,11.0,1264.0,271.0,370.0,177.0,1.3000,69700.0
2740,-119.97,36.44,18.0,1128.0,237.0,772.0,220.0,2.1771,39200.0
2779,-119.01,35.40,11.0,8739.0,2190.0,4781.0,1919.0,1.7109,44600.0
2902,-118.48,35.61,17.0,4002.0,930.0,1614.0,731.0,1.6236,67300.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0

In [29]:
'''Задача №61. Решение в группах
1. Определить какое максимальное и минимальное
значение median_house_value
2. Показать максимальное median_house_value, где
median_income = 3.1250
3. Узнать какая максимальная population в зоне
минимального значения median_house_value
'''
print('Max =', datafr['median_house_value'].max(), 'Min =', datafr['median_house_value'].min())

Max = 500001.0 Min = 22500.0

In [33]:
datafr[(datafr['median_income'] == 3.1250)][['median_house_value']]

      median_house_value
207             167100.0
784             233300.0
904             156300.0
1908            219900.0

In [ ]:
datafr[(datafr['median_income'] == 3.1250) & (datafr['median_house_value'].max()), 'median_house_value']

In [42]:
datafr[(datafr['median_house_value'] == datafr['median_house_value'].min())]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2001,-117.16,32.71,52.0,845.0,451.0,1230.0,375.0,1.0918,22500.0

In [47]:
datafr['total_result']=0

In [58]:
datafr

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,total_result,total_new,total_new1
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,rich,60600.0,2
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,middle,27700.0,1
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,rich,49500.0,1
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,rich,1100.0,0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,middle,23700.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,poor,60700.0,2
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,middle,103600.0,2
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,middle,22000.0,1
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,middle,1400.0,0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,rich,26000.0,1

In [50]:
datafr['total_new']= datafr['households'].apply (lambda x: x*100)

In [55]:
datafr.loc [(datafr['median_income']>5), 'total_result'] = 'rich'
datafr.loc [(datafr['median_income']>=2)&(datafr['median_income']<=5), 'total_result'] = 'middle'
datafr.loc [(datafr['median_income']<2), 'total_result'] = 'poor'

In [57]:
def func (x):
  if x<200:
    res = 0
  elif 200<= x <500:
    res = 1
  else:
    res = 2
  return res
datafr['total_new1']= datafr['households'].apply (func)

In [ ]:
'''Задача 40: Работать с файлом california_housing_train.csv, который находится в папке
sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)
'''
datafr[(datafr['median_house_value'].mean()) & (0<=datafr['population']<=500), 'median_house_value']

In [ ]:
'''
Задача 42: Узнать какая максимальная households в зоне минимального значения population
'''
datafr[(datafr['households'].max()) & (datafr['population'].min()), 'households']